name: deploy-to-server
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build-and-deploy:
    name: Build and Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run tsc
# taken from https://stackoverflow.com/a/64210623/4188138
      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
      - name: list files for rsync
        shell: bash
        run: find dist server -type f >> rsync_list.txt
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete --files-from='rsync_list.txt' --exclude="*.db"
          path: dist
          remote_path: /home/ec2-user/${{ env.BRANCH_NAME }}
          remote_host: ec2-3-10-151-65.eu-west-2.compute.amazonaws.com
          remote_port: 22
          remote_user: ec2-user
          remote_key: ${{ secrets.DEPLOY_KEY }}
  restart-server:
    name: Restart Server
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: run-restart-script
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-10-151-65.eu-west-2.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: /usr/bin/bash /home/ec2-user/${{ env.BRANCH_NAME }}/server/restart_server.sh